### ISSUE TITLE
Symmetry bounding box issue

### ISSUE THREAD

**Issue by zacharyfmarion** [robbykraft/grapher#3]
When I set a symmetry line and then try to draw a line I get an unhandled exception that makes the app unusable until I refresh - it looks like it's coming from calling `boundingBox` when some of the `vertices_coords` are NaN. Not sure how that is possible - an easy fix would just be to filter those out, but I'm guessing the root cause is that they get added in the first place.

<img width="264" alt="Screenshot 2024-06-15 at 5 39 38 PM" src="https://github.com/rabbit-ear/rabbit-ear-app/assets/9957046/9a6cdac9-83cb-433d-abe8-44b16e4ad73a">

Steps to repro:

1. Create a new frame (16x16 grid)
2. Click on the symmetry tool and draw a book symmetry line
3. Switch to the line tool and draw a line on the left side - `graphToMatrix2` gets passed a graph with a `vertices_coords` array that contains NaN

**Comment by zacharyfmarion** [comment]
Janky fix would be to add this to `rabbit-ear`:

```diff
diff --git a/src/math/polygon.js b/src/math/polygon.js
index ef147cbd..4cff60bc 100644
--- a/src/math/polygon.js
+++ b/src/math/polygon.js
@@ -196,7 +196,7 @@ export const boundingBox = (points, padding = 0) => {
        const min = Array(dimension).fill(Infinity);
        const max = Array(dimension).fill(-Infinity);
        points
-               .filter(p => p !== undefined)
+               .filter(p => Array.isArray(p))
                .forEach(point => point
                        .forEach((c, i) => {
                                if (c < min[i]) { min[i] = c - padding; }
```

But the actual symmetry tool doesn't seem to be working

**Comment by amkraft** [comment]
great catch! I can reproduce the error. Looking into it now..

**Comment by amkraft** [comment]
figured it out. at some point I modified the drawing api for `segment`

```js
segment([0, 1], [4, 5])
// to
segment([[0, 1], [4, 5]])
```
and didn't realize it affected the symmetry tool.

thanks for catching this!
