### ISSUE TITLE
Enabling prettier

### ISSUE THREAD

**Issue by zacharyfmarion** [robbykraft/grapher#5]
@mayakraft Would you be opposed to enabling prettier so that formatting is consistent across contributions? My editor auto-formats the code that I change and it would be good to standardize if you are open to contributions. I'm happy to open a PR!

**Comment by amkraft** [comment]
Sure! happy to merge a PR if you want to set it up. I have one preference, can it use tabs, not spaces? That's really my only preference regarding formatting if that's alright.
